[platformio]
core_dir = ../../.pio-core

[env:nodemcu-32s]
platform = espressif32@6.8.1
board = nodemcu-32s
framework = espidf
monitor_speed = 115200
; Cross-platform serial port settings:
; Linux example:   pio run -t upload --upload-port /dev/ttyUSB0
; Windows example: pio run -t upload --upload-port COM3
