/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#faf8ff",
        "primary-fixed-dim": "#b3c5ff",
        tertiary: "#a33200",
        "tertiary-fixed": "#ffdbd0",
        "on-primary-fixed": "#001849",
        "surface-container": "#ecedfa",
        "secondary-container": "#d0e1fb",
        "on-error": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "on-primary-container": "#f8f7ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff0fd",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb59d",
        primary: "#0050cb",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-container": "#fff6f4",
        "surface-container-high": "#e6e7f4",
        "primary-container": "#0066ff",
        background: "#faf8ff",
        "on-secondary-fixed": "#0b1c30",
        "inverse-surface": "#2e303a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#003fa4",
        "surface-dim": "#d8d9e6",
        "on-surface-variant": "#424656",
        "on-secondary": "#ffffff",
        secondary: "#505f76",
        "inverse-primary": "#b3c5ff",
        "on-surface": "#191b24",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#390c00",
        outline: "#727687",
        "primary-fixed": "#dae1ff",
        "surface-tint": "#0054d6",
        surface: "#faf8ff",
        "on-secondary-container": "#54647a",
        "surface-variant": "#e1e2ee",
        "tertiary-container": "#cc4204",
        "on-tertiary-fixed-variant": "#832600",
        "surface-container-highest": "#e1e2ee",
        "on-secondary-fixed-variant": "#38485d",
        "on-background": "#191b24",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c6d8",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        base: "4px",
        gutter: "20px",
        lg: "24px",
        sm: "8px",
        margin: "24px",
        xl: "32px",
      },
      fontFamily: {
        "status-label": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-data": ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "status-label": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-data": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
  plugins: [],
};
